### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by ranrui-y** [Nwflower/Atlas#14]
有没有help？

**Comment by Nwflower** [comment]
咋，你看不懂readme吗

**Comment by ranrui-y** [comment]
我指的是有没有这种
![Uploading -3420ee2459e7a427.jpg…]()

**Comment by ranrui-y** [comment]
> 咋，你看不懂readme吗
我指的是有没有这种
![Uploading -3420ee2459e7a427.jpg…]()

**Comment by ranrui-y** [comment]
> 咋，你看不懂readme吗

我指的是有没有这种
![Uploading -3420ee2459e7a427.jpg…]()

**Comment by Nwflower** [comment]
没有帮助菜单

**Comment by ranrui-y** [comment]
> 

我更想要设置菜单。
崩坏铁道图鉴好像有点问题

```
黑塔:

  - 阿蓝

[10:26:45.519][ERRO] YAMLParseError: Map keys must be unique at line 144, column 1:

[10:26:45.517][ERRO] [Atlas图鉴][atlas]

    at parseDocument (/root/Miao-Yunzai/node_modules/.pnpm/yaml@2.2.1/node_modules/yaml/dist/public-api.js:45:16)

    at compose.next (<anonymous>)

    at Composer.compose (/root/Miao-Yunzai/node_modules/.pnpm/yaml@2.2.1/node_modules/yaml/dist/compose/composer.js:131:25)

    at next (<anonymous>)

    at Composer.next (/root/Miao-Yunzai/node_modules/.pnpm/yaml@2.2.1/node_modules/yaml/dist/compose/composer.js:149:40)

    at Object.composeDoc (/root/Miao-Yunzai/node_modules/.pnpm/yaml@2.2.1/node_modules/yaml/dist/compose/compose-doc.js:32:23)

    at Object.composeNode (/root/Miao-Yunzai/node_modules/.pnpm/yaml@2.2.1/node_modules/yaml/dist/compose/compose-node.js:31:38)

    at Object.composeCollection (/root/Miao-Yunzai/node_modules/.pnpm/yaml@2.2.1/node_modules/yaml/dist/compose/compose-collection.js:13:36)

    at Object.resolveBlockMap (/root/Miao-Yunzai/node_modules/.pnpm/yaml@2.2.1/node_modules/yaml/dist/compose/resolve-block-map.js:60:13)

    at Composer.onError (/root/Miao-Yunzai/node_modules/.pnpm/yaml@2.2.1/node_modules/yaml/dist/compose/composer.js:69:34)

^


```

**Comment by Nwflower** [comment]
菜单指令为：#图鉴帮助
此外，及时更新插件，指令为#全部更新
